HTML Разметка всех страниц
htmlacademy-adaptive/2050153-sedona-27 pull request #2
Opened 2022-12-04 04:04 UTC by NataliZin85

2022-12-05 13:27 UTC, Dima-Dim requested changes
source/img/Checkbox-icon.svg - не нужно использовать буквы в разных регистрах в названиях файлов и папок.

source/img/text-sedona-icon-full-screen.svg - уверена что не достаточно 1-ой svg которой можно указать разные размеры, в зависимости от необходимости?

Провериться валидатором validator.w3.org/nu/

2022-12-05 13:27 UTC, Dima-Dim commented on source/index.html
> +          <li class="advantages__item advantages__item--image">
Это не отдельный самодосаточный пункт списка.

2022-12-05 13:27 UTC, Dima-Dim commented on source/index.html
> +              бургер, вы не
Зачем тут переносы строк?

2022-12-05 13:27 UTC, Dima-Dim commented on source/index.html
> +        <ul class="advantage__list advantages__list--with-image">
`advantage__list` -> `advantages__list` и в других местах так же.

2022-12-05 13:27 UTC, Dima-Dim commented on source/index.html
> +            <a class="footer-social__button button__vk link" href="https://vk.com/htmlacademy">
`button__vk` -> `footer-social__button--vk`

2022-12-05 13:27 UTC, Dima-Dim commented on source/form.html
> +        <fieldset class="feedback-form__form-group form-group form-group__personal-form personal-form">
Тег одновременно и блок и элемент этого блока? Это перебор. Ещё одновременно несколькими блоками является? Сейчас лучше очень сильно не доставить классов, чем потом искать те, которые не нужны.

2022-12-05 13:27 UTC, Dima-Dim commented on source/form.html
> +    <section class="form__feedback-form feedback-form">
Элемент `form__feedback-form` - вне тега `form`. Проверять тут yoksel.github.io/html-tree/

2022-12-07 01:29 UTC, NataliZin85 commented on source/index.html
> +          <li class="advantages__item advantages__item--image">
Почему? мы же можем прописывать разные фотографии... Не пойму логики, можно пояснить пожалуйста

2022-12-07 01:36 UTC, NataliZin85 commented on source/index.html
> +        <ul class="advantage__list advantages__list--with-image">
Не поняла, это разные: в первом случае это общий, во втором advantages__list--with-image - это частное, где прописывается синий background...
В чем здесь проблема?

2022-12-07 01:39 UTC, NataliZin85 commented on source/index.html
> +        <ul class="advantage__list advantages__list--with-image">
поняла

2022-12-09 09:20 UTC, Dima-Dim commented on source/index.html
> +          <li class="advantages__item advantages__item--image">
Это не сама по себе фотография, это иллюстрация пункта "Настоящий городок".

2022-12-09 15:44 UTC, Dima-Dim requested changes

2022-12-09 15:44 UTC, Dima-Dim commented on source/form.html
> +          <textarea class="form-group__field feedback-free-form__field" type="text" name="message"
```
Error: Attribute type not allowed on element [textarea](https://html.spec.whatwg.org/multipage/#the-textarea-element) at this point.
```
validator.w3.org/nu/

2022-12-09 15:44 UTC, Dima-Dim commented on source/form.html
> +    <section class="section__feedback-form feedback-form">
Элемент `section__feedback-form` вне блока `section`. А если бы и был блок с названием `section` то это довольно странный блок, по этому даже не знаю что тут имелось ввиду.
Далее так же есть ошибки по БЭМ, которые можно проверить вот тут:
yoksel.github.io/html-tree/

2022-12-10 07:37 UTC, merged