Стилизация
htmlacademy-adaptive/2050153-sedona-27 pull request #3
Opened 2022-12-17 02:50 UTC by NataliZin85

2022-12-26 14:29 UTC, Dima-Dim requested changes

2022-12-26 14:29 UTC, Dima-Dim commented on source/catalog.html
> +        <button class="toggle-buttons__toggle toggle-buttons__toggle-open toggle-buttons__toggle-current" type="button">
`toggle-open` и `toggle-current` это модификаторы. И `toggle` в них лишнее. Достаточно `toggle-buttons--open`.
`toggle-buttons__toggle` - Элемент тогл блока тогловых кнопок? Явно что-то не то с названием блока. Оно должно быть таким, что его читаешь и понятно что это за блок, а потом и элемент.

2022-12-26 14:29 UTC, Dima-Dim commented on source/catalog.html
> +        <ul class="nav__list site-list nav-list">
Одновременно и блок `site-list` и `nav-list`? Так не должно быть.

2022-12-26 14:29 UTC, Dima-Dim commented on source/catalog.html
> +          <li class="site-list__item nav-list__item">
Ну и что тег это одновременно и элемент одного блока и элемент другого блока тоже.

2022-12-26 14:29 UTC, Dima-Dim commented on source/catalog.html
> +    <section class="catalog__hero hero hero-catalog">
Так же тег не может быть одновременно и блоком и элементов этого блока. Это просто не логично.

2022-12-26 14:29 UTC, Dima-Dim commented on source/catalog.html
> +      <div class="hero__wrapper hero-catalog__wrapper">
Тут тоже элемент одного блока и элемент другого блока. Не должно так быть.

2022-12-27 13:59 UTC, Dima-Dim reviewed
Пустых файлов блоков так же быть не должно. Если он пустой, значит он не нужен.
И не забывай обращать внимание на змечания линтера.

2022-12-27 13:59 UTC, Dima-Dim commented on source/index.html
>                  <h4 class="advantages__title advantages-reasons__title">еда</h4>
Ненужно на одном теге использовать элементы от разных блоков. В данном случае это уже не элемент `advantages`, `advantages` был далек сверху. Тоже самое касается и других подобных мест.

2022-12-27 13:59 UTC, Dima-Dim commented on source/sass/advantages-with-numbers.scss
> +  .advantages__title {
Во-первых, это селектор из другого блока.
Во-вторых, https://up.htmlacademy.ru/adaptive/27/criteries#d11, если ты не прописала явно `&`, это не значит что его логика тут не используется.

2022-12-27 13:59 UTC, Dima-Dim commented on source/sass/catalog.scss
> +.catalog__hero {
Ну нет :) Если нет свойств, то и класса нет. Не нужно прописывать классы прозапас.

2022-12-27 13:59 UTC, Dima-Dim commented on source/sass/page__body.scss
> +.page__body {
В нашем БЭМ-е нет файлов для элементов :) Т.е. он должен называться [page__body.scss](https://github.com/htmlacademy-adaptive/2050153-sedona-27/pull/3/files#diff-7ae73beb702a8733377d9dd1a798f04b85847757a71bf69e1e559ab18909d7f2) но такой файл уже есть, стало быть этот код нужно перенести в него.

2022-12-27 13:59 UTC, Dima-Dim commented on source/sass/site-list.scss
> +.site__list {
Либо`site__list` -> `site-list`, либо это другой блок и другой файл.

2022-12-28 00:32 UTC, NataliZin85 commented on source/index.html
>                  <h4 class="advantages__title advantages-reasons__title">еда</h4>
как это прописывать тогда? я еще не знаю как прописывать повторяющиеся элементы. Либо ты меня учи, либо жди, когда я до этого места доберусь в обучении.

2022-12-28 00:32 UTC, NataliZin85 commented on source/sass/advantages-with-numbers.scss
> +  .advantages__title {
это был экспиремент, напиши мне тогда как я должна была прописывать.

2022-12-28 09:53 UTC, merged

2022-12-29 09:22 UTC, Dima-Dim commented on source/index.html
>                  <h4 class="advantages__title advantages-reasons__title">еда</h4>
Дело не в повторяющихся элементах, а в том что не нужно усложнять БЭМ, там где этого не требуется. Этот тег либо самостоятельный блок и за одно чей-то элемент, либо просто чей-то элемент. При необходимости тут может быть и модификатор. Но тут этот тег точно может не быть одновременно элементом разных блоков. Для чего тут это? Какие свойства будут относится к `advantages__title`, а какие к `advantages-reasons__title`? Почему все они не могут быть у `advantages-reasons__title`?
Если речь про то, что этот тег может быть похожим образом стилизован в рамках другого блока, то может тогда это в первую очередь всё же блок?

2022-12-29 09:28 UTC, Dima-Dim commented on source/sass/advantages-with-numbers.scss
> +  .advantages__title {
Должно быть как сказано в критерии https://up.htmlacademy.ru/adaptive/27/criteries#d11, в данном конкретном случае, может быть
```
.advantages-with-numbers__item .advantages__title {
}
```
но это всё ещё нарушает БЭМ, в соответствии с которым в файле для блока `.advantages-with-numbers` не может быть селекторов блока `advantages`. Т.е. нарушена логика самодостаточности блока `advantages`, сейчас его стилизация зависит от блока `advantages-with-numbers` и такого быть не должно.
Чтобы этого избежать, тут могло бы быть
```
.advantages-with-numbers__item .advantages-with-numbers__title {
}
```