адаптивная сетка-медиа
htmlacademy-adaptive/2050153-sedona-27 pull request #4
Opened 2022-12-29 01:12 UTC by NataliZin85

2023-01-03 12:12 UTC, Dima-Dim requested changes

2023-01-03 12:12 UTC, Dima-Dim commented on source/form.html
>            <legend class="form-group__title checkbox-form__title">Посещенные достопримечательности:</legend>
Элемент `checkbox-form__title` вне блока `checkbox-form`
yoksel.github.io/html-tree/
и как писал ранее, не нужно делать один тег элементами разных блоков.

2023-01-03 12:12 UTC, Dima-Dim commented on source/sass/blocks/advantages-with-numbers.scss
> +  .advantages__title {
Во-первых, это нарушает https://up.htmlacademy.ru/adaptive/27/criteries#d11
Во-вторых, в этом файле должны быть селекторы только для блока `advantages-with-numbers`.

2023-01-03 12:12 UTC, Dima-Dim commented on source/sass/blocks/photos-catalog.scss
> +  .photos-catalog__image {
https://up.htmlacademy.ru/adaptive/27/criteries#d11

2023-01-03 12:12 UTC, Dima-Dim commented on source/sass/blocks/site-list.scss
> +@media (min-width: variables.$tablet-width) {
Нужно писать код единообразно. У тебя везде медиавыражения внутри селекторов, а тут они снаружи.

2023-01-06 06:11 UTC, NataliZin85 commented on source/sass/blocks/photos-catalog.scss
> +  .photos-catalog__image {
Как тогда мне это реализовать? пока не знаю как прописать

2023-01-06 12:57 UTC, Dima-Dim commented on source/sass/blocks/photos-catalog.scss
> +  .photos-catalog__image {
Можно вот так:
```
.photos-catalog__item:first-child .photos-catalog__image {
}
```

2023-01-09 08:08 UTC, merged